laurenceob/pension-inequalities-code

- clean_usoc.do
- extract_usoc.do
- master.do
> 1 create clean usoc dataset before jack starts

- README.md
> PR for #3: Update readme file

- analysis.do
Closes #5
[inequalities notes.pdf](https://github.com/laurenceob/pension-inequalities-code/files/9002614/inequalities.notes.pdf)
> PR for #5: 5-make-graph-of-pension-membership-by-ethnicity

- analysis.do
Closes #11 
Created graphs for: 
- Pension membership/contribution rate over age by: race, sector, health status
- Age distribution by race
Created tables using esttab:
- Pension membership/contribution rate by race, controlling for age FE's
- Age distribution (mean, sd) by race
[inequalities notes.pdf](https://github.com/laurenceob/pension-inequalities-code/files/9019359/inequalities.notes.pdf)
> PR for #11: examine how age affects pension inequalities

- analysis.do
Closes #13 
[inequalities notes.pdf](https://github.com/laurenceob/pension-inequalities-code/files/9020313/inequalities.notes.pdf)
Created graphs for pensions over time
> #13: analyse pension membershpcontribution rate over time

- analysis.do
Closes #17 
Have decomposed pension contribution difference in age for health status and explained the output. In future will neaten up table, and do for the rest of the variables e.g race, sector...
[inequalities notes.pdf](https://github.com/laurenceob/pension-inequalities-code/files/9028993/inequalities.notes.pdf)
> #17: decomposition

- analysis.do
closes #16
[inequalities notes.pdf](https://github.com/laurenceob/pension-inequalities-code/files/9030109/inequalities.notes.pdf)
Created plot of age distribution by region and education level, and plotted pension contribution rates/membership by age group for education groups.
> PR for #16:do analysis by age and time for region and education

- analysis.do
Closes #15 
Created 2 tables looking at the sample size for the age categories (variables age_dum with 10 and age_dum_1 with 4) by race.
[inequalities notes.pdf](https://github.com/laurenceob/pension-inequalities-code/files/9038205/inequalities.notes.pdf)
> #15: look into sample sizes by race and age group

- analysis.do
closes #20 
Created graphs for pension saving/membership over income group by health status. Started creating regression output tables for other variables e.g. by race.
[inequalities notes.pdf](https://github.com/laurenceob/pension-inequalities-code/files/9040711/inequalities.notes.pdf)
> PR for #20:exploring pensions inequality by health

- analysis.do
Closes #23
[inequalities notes.pdf](https://github.com/laurenceob/pension-inequalities-code/files/9047971/inequalities.notes.pdf)
> PR for #23: resolve issues

- analysis.do
Completed all STATA tasks for presentation prep - now writing up findings in latex doc.
[inequalities notes.pdf](https://github.com/laurenceob/pension-inequalities-code/files/9054264/inequalities.notes.pdf)
> PR for #25: presentation prep

- analysis.do
- clean_usoc.do
> PR for #27: short term analysis tasks

- analysis.do
closes #30
[Uploading inequalities notes.pdf…]()
> PR for #30: analysis tasks

- analysis.do
Closes #32
[inequalities notes.pdf](https://github.com/laurenceob/pension-inequalities-code/files/9072564/inequalities.notes.pdf)
> PR for #32:covariates table and update clean usoc

- analysis.do
- clean_usoc.do
closes #35 
[inequalities notes.pdf](https://github.com/laurenceob/pension-inequalities-code/files/9084060/inequalities.notes.pdf)
> PR for #35: update clean usoc

- analysis.do
- clean_usoc.do
closes #37
[inequalities notes.pdf](https://github.com/laurenceob/pension-inequalities-code/files/9100550/inequalities.notes.pdf)
> #37: changes from meeting

- analysis.do
- clean_usoc.do
closes #39
[inequalities notes.pdf](https://github.com/laurenceob/pension-inequalities-code/files/9119605/inequalities.notes.pdf)
> PR for #39: further changes

- analysis.do
[Pension Inequalities 2.1 - Jack.pptx](https://github.com/laurenceob/pension-inequalities-code/files/9158441/Pension.Inequalities.2.1.-.Jack.pptx)
closes #41
> PR for #41: export graphs for powerpoint

- analysis.do
closes #47 
[Presentation script.docx](https://github.com/laurenceob/pension-inequalities-code/files/9200506/Presentation.script.docx)
[Pension Inequalities 2.1 - Jack edit.pptx](https://github.com/laurenceob/pension-inequalities-code/files/9200507/Pension.Inequalities.2.1.-.Jack.edit.pptx)
> PR for #47: presentation edit

- analysis.do
> PR for #49: create bar chart

- README_JACK.txt
- analysis_usoc.do
closes #52 
Cleaned do file, changed name to analysis_usoc so consistent with master do file. Added comments so clearer.
> PR for #52: clean do file

- analysis_usoc.do
> PR for #55: public sector analysis

- analysis_usoc.do
> PR for #59: self employed analysis

- analysis_usoc.do
- clean_usoc.do
> PR for #61: clean religion variable and add as control

- analysis_usoc.do
- clean_usoc.do
> PR for #64: create average earnings
